Repository boostorg/uuid, pull requests merged in 2019-04, with the labels that each got.

#101 Refresh CI scripts
  .travis.yml
  appveyor.yml
Labels: ci

#95 Fixes https://github.com/boostorg/uuid/issues/94
  include/boost/uuid/detail/random_provider_bcrypt.ipp
  include/boost/uuid/detail/random_provider_wincrypt.ipp
Labels: bug

#97 Disable getentropy backend on Linux and Android
  include/boost/uuid/detail/random_provider_detect_platform.hpp
Labels: bug

#100 Implement std::hash in terms of hash_value.
  include/boost/uuid/uuid_hash.hpp
Labels: enhancement
